//go:generate go run ./cmd/generate-project-list
// THIS FILE IS AUTO-GENERATED WITH 'go generate .'
package dashboard

var defaultProjects = []*Project{
	{
		Name:          "jekyll",
		Nwo:           "jekyll/jekyll",
		Branch:        "master",
		GemName:       "jekyll",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk2NTI1Mg==",
	},
	{
		Name:          "jekyll-admin",
		Nwo:           "jekyll/jekyll-admin",
		Branch:        "master",
		GemName:       "jekyll-admin",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk1OTIyNzUyOA==",
	},
	{
		Name:          "jekyll-feed",
		Nwo:           "jekyll/jekyll-feed",
		Branch:        "master",
		GemName:       "jekyll-feed",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkzNTQ4OTU2Nw==",
	},
	{
		Name:          "jekyll-compose",
		Nwo:           "jekyll/jekyll-compose",
		Branch:        "master",
		GemName:       "jekyll-compose",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxOTY1MDIwNA==",
	},
	{
		Name:          "classifier-reborn",
		Nwo:           "jekyll/classifier-reborn",
		Branch:        "master",
		GemName:       "classifier-reborn",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMjgxODQ0MQ==",
	},
	{
		Name:          "jekyll-import",
		Nwo:           "jekyll/jekyll-import",
		Branch:        "master",
		GemName:       "jekyll-import",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk3OTIzNDQz",
	},
	{
		Name:          "jekyll-archives",
		Nwo:           "jekyll/jekyll-archives",
		Branch:        "master",
		GemName:       "jekyll-archives",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMzA1MTM2OQ==",
	},
	{
		Name:          "jekyll-gist",
		Nwo:           "jekyll/jekyll-gist",
		Branch:        "master",
		GemName:       "jekyll-gist",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMDM4MTY4Nw==",
	},
	{
		Name:          "github-metadata",
		Nwo:           "jekyll/github-metadata",
		Branch:        "master",
		GemName:       "github-metadata",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyNDA4ODIxNA==",
	},
	{
		Name:          "jekyll-mentions",
		Nwo:           "jekyll/jekyll-mentions",
		Branch:        "master",
		GemName:       "jekyll-mentions",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNjA1Mzk5NA==",
	},
	{
		Name:          "jekyll-avatar",
		Nwo:           "jekyll/jekyll-avatar",
		Branch:        "main",
		GemName:       "jekyll-avatar",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk0OTM3ODE0Ng==",
	},
	{
		Name:          "jekyll-coffeescript",
		Nwo:           "jekyll/jekyll-coffeescript",
		Branch:        "master",
		GemName:       "jekyll-coffeescript",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNjI0MjcxOA==",
	},
	{
		Name:          "jekyll-opal",
		Nwo:           "jekyll/jekyll-opal",
		Branch:        "master",
		GemName:       "jekyll-opal",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMDg3MjQwMw==",
	},
	{
		Name:          "jekyll-docs",
		Nwo:           "jekyll/jekyll-docs",
		Branch:        "master",
		GemName:       "jekyll-docs",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyODU3MDA4MA==",
	},
	{
		Name:          "directory",
		Nwo:           "jekyll/directory",
		Branch:        "master",
		GemName:       "directory",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxMTI2NTcwOQ==",
	},
	{
		Name:          "jekyll-commonmark",
		Nwo:           "jekyll/jekyll-commonmark",
		Branch:        "master",
		GemName:       "jekyll-commonmark",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk0ODQwMTA3Mw==",
	},
}
