//go:generate go run ./cmd/generate-project-list
// THIS FILE IS AUTO-GENERATED WITH 'go generate .'
// LAST UPDATED Aug 22, 2022 01:17:04 UTC
package dashboard

var defaultProjects = []*Project{
	{
		Name:          "jekyll",
		Nwo:           "jekyll/jekyll",
		Branch:        "master",
		GemName:       "jekyll",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk2NTI1Mg==",
	},
	{
		Name:          "minima",
		Nwo:           "jekyll/minima",
		Branch:        "master",
		GemName:       "minima",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk1OTMzMTM5NQ==",
	},
	{
		Name:          "jekyll-admin",
		Nwo:           "jekyll/jekyll-admin",
		Branch:        "master",
		GemName:       "jekyll-admin",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk1OTIyNzUyOA==",
	},
	{
		Name:          "jekyll-seo-tag",
		Nwo:           "jekyll/jekyll-seo-tag",
		Branch:        "master",
		GemName:       "jekyll-seo-tag",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk0NDkzMTMxMw==",
	},
	{
		Name:          "jekyll-sitemap",
		Nwo:           "jekyll/jekyll-sitemap",
		Branch:        "master",
		GemName:       "jekyll-sitemap",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNzMyNzUzNQ==",
	},
	{
		Name:          "jekyll-feed",
		Nwo:           "jekyll/jekyll-feed",
		Branch:        "master",
		GemName:       "jekyll-feed",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkzNTQ4OTU2Nw==",
	},
	{
		Name:          "jekyll-redirect-from",
		Nwo:           "jekyll/jekyll-redirect-from",
		Branch:        "master",
		GemName:       "jekyll-redirect-from",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNTIwODUxNA==",
	},
	{
		Name:          "jekyll-compose",
		Nwo:           "jekyll/jekyll-compose",
		Branch:        "master",
		GemName:       "jekyll-compose",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxOTY1MDIwNA==",
	},
	{
		Name:          "classifier-reborn",
		Nwo:           "jekyll/classifier-reborn",
		Branch:        "master",
		GemName:       "classifier-reborn",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMjgxODQ0MQ==",
	},
	{
		Name:          "jemoji",
		Nwo:           "jekyll/jemoji",
		Branch:        "master",
		GemName:       "jemoji",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNTY1NzU3OA==",
	},
	{
		Name:          "jekyll-import",
		Nwo:           "jekyll/jekyll-import",
		Branch:        "master",
		GemName:       "jekyll-import",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk3OTIzNDQz",
	},
	{
		Name:          "jekyll-archives",
		Nwo:           "jekyll/jekyll-archives",
		Branch:        "master",
		GemName:       "jekyll-archives",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMzA1MTM2OQ==",
	},
	{
		Name:          "jekyll-gist",
		Nwo:           "jekyll/jekyll-gist",
		Branch:        "master",
		GemName:       "jekyll-gist",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMDM4MTY4Nw==",
	},
	{
		Name:          "github-metadata",
		Nwo:           "jekyll/github-metadata",
		Branch:        "main",
		GemName:       "jekyll-github-metadata",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyNDA4ODIxNA==",
	},
	{
		Name:          "jekyll-mentions",
		Nwo:           "jekyll/jekyll-mentions",
		Branch:        "master",
		GemName:       "jekyll-mentions",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNjA1Mzk5NA==",
	},
	{
		Name:          "jekyll-sass-converter",
		Nwo:           "jekyll/jekyll-sass-converter",
		Branch:        "master",
		GemName:       "jekyll-sass-converter",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNjI0MzU3MA==",
	},
	{
		Name:          "mercenary",
		Nwo:           "jekyll/mercenary",
		Branch:        "master",
		GemName:       "mercenary",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNDE4MzUwNA==",
	},
	{
		Name:          "jekyll-paginate",
		Nwo:           "jekyll/jekyll-paginate",
		Branch:        "master",
		GemName:       "jekyll-paginate",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMDE5MjY4Ng==",
	},
	{
		Name:          "jekyll-watch",
		Nwo:           "jekyll/jekyll-watch",
		Branch:        "master",
		GemName:       "jekyll-watch",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMTI1NzI4Mg==",
	},
	{
		Name:          "jekyll-avatar",
		Nwo:           "jekyll/jekyll-avatar",
		Branch:        "main",
		GemName:       "jekyll-avatar",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk0OTM3ODE0Ng==",
	},
	{
		Name:          "jekyll-coffeescript",
		Nwo:           "jekyll/jekyll-coffeescript",
		Branch:        "master",
		GemName:       "jekyll-coffeescript",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxNjI0MjcxOA==",
	},
	{
		Name:          "jekyll-opal",
		Nwo:           "jekyll/jekyll-opal",
		Branch:        "master",
		GemName:       "jekyll-opal",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyMDg3MjQwMw==",
	},
	{
		Name:          "jekyll-docs",
		Nwo:           "jekyll/jekyll-docs",
		Branch:        "master",
		GemName:       "jekyll-docs",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyODU3MDA4MA==",
	},
	{
		Name:          "jekyll-commonmark",
		Nwo:           "jekyll/jekyll-commonmark",
		Branch:        "master",
		GemName:       "jekyll-commonmark",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnk0ODQwMTA3Mw==",
	},
	{
		Name:          "directory",
		Nwo:           "jekyll/directory",
		Branch:        "master",
		GemName:       "",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkxMTI2NTcwOQ==",
	},
	{
		Name:          "jekyll-textile-converter",
		Nwo:           "jekyll/jekyll-textile-converter",
		Branch:        "master",
		GemName:       "jekyll-textile-converter",
		GlobalRelayID: "MDEwOlJlcG9zaXRvcnkyOTQwMzM1Ng==",
	},
}
