---
on:
- push
- pull_request
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.25" # ideally matches Heroku
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Test
      run: go test ./...
    - name: Compile
      run: go build ./...
